/* tslint:disable */
/* eslint-disable */
/**
 * Assignment 2 - User Login Service API
 * Assignment 2 用户登录服务 MVP - API规范文档  这是一个基于 Go Gin 框架构建的用户认证服务，提供登录和用户信息获取功能。  ## 特性 - JWT token 认证 - Bcrypt 密码加密 - RESTful API 设计 - CORS 支持  ## 认证流程 1. 用户通过 `/user/login` 接口进行身份验证 2. 服务器验证用户名和密码，返回 JWT token 3. 客户端在后续请求中通过 `Authorization: Bearer <token>` 头部携带 token 4. 服务器验证 token 有效性，提供相应的服务 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developer@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  LoginUser200Response,
  LoginUserRequest,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    LoginUser200ResponseFromJSON,
    LoginUser200ResponseToJSON,
    LoginUserRequestFromJSON,
    LoginUserRequestToJSON,
} from '../models/index';

export interface LoginUserOperationRequest {
    loginUserRequest: LoginUserRequest;
}

/**
 * 
 */
export class AuthenticationApi extends runtime.BaseAPI {

    /**
     * 用户身份认证接口。验证用户名和密码，成功后返回 JWT 访问令牌。  ## 认证机制 - 使用 bcrypt 进行密码哈希验证 - JWT token 有效期为 24 小时 - 支持的测试账户：   - admin / password123   - user1 / mypassword 
     * 用户登录
     */
    async loginUserRaw(requestParameters: LoginUserOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginUser200Response>> {
        if (requestParameters['loginUserRequest'] == null) {
            throw new runtime.RequiredError(
                'loginUserRequest',
                'Required parameter "loginUserRequest" was null or undefined when calling loginUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/user/login`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginUserRequestToJSON(requestParameters['loginUserRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginUser200ResponseFromJSON(jsonValue));
    }

    /**
     * 用户身份认证接口。验证用户名和密码，成功后返回 JWT 访问令牌。  ## 认证机制 - 使用 bcrypt 进行密码哈希验证 - JWT token 有效期为 24 小时 - 支持的测试账户：   - admin / password123   - user1 / mypassword 
     * 用户登录
     */
    async loginUser(requestParameters: LoginUserOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginUser200Response> {
        const response = await this.loginUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
