/* tslint:disable */
/* eslint-disable */
/**
 * Assignment 3 - Blog System API
 * Assignment 3 Milestone 1 博客系统 MVP - API规范文档  这是一个基于 Go Gin 框架构建的博客系统，提供用户认证、博文创建和浏览功能。  ## 特性 - JWT token 认证 - Bcrypt 密码加密 - GORM 数据库持久化 - 博文创建和列表 - RESTful API 设计 - CORS 支持  ## 认证流程 1. 用户通过 `/user/login` 接口进行身份验证 2. 服务器验证用户名和密码，返回 JWT token 3. 客户端在后续请求中通过 `Authorization: Bearer <token>` 头部携带 token 4. 服务器验证 token 有效性，提供相应的服务 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: developer@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  GetUserInfo200Response,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    GetUserInfo200ResponseFromJSON,
    GetUserInfo200ResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class UserInformationApi extends runtime.BaseAPI {

    /**
     * 获取当前登录用户的个人信息。需要在请求头中提供有效的 JWT token。  ## 认证要求 - 必须在 Authorization 头部提供 Bearer token - Token 格式：`Bearer <jwt_token>` - Token 必须有效且未过期 
     * 获取用户信息
     */
    async getUserInfoRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetUserInfo200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/user/info`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetUserInfo200ResponseFromJSON(jsonValue));
    }

    /**
     * 获取当前登录用户的个人信息。需要在请求头中提供有效的 JWT token。  ## 认证要求 - 必须在 Authorization 头部提供 Bearer token - Token 格式：`Bearer <jwt_token>` - Token 必须有效且未过期 
     * 获取用户信息
     */
    async getUserInfo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetUserInfo200Response> {
        const response = await this.getUserInfoRaw(initOverrides);
        return await response.value();
    }

}
