/* tslint:disable */
/* eslint-disable */
/**
 * Assignment 3 - Blog System API
 * Assignment 3 Milestone 1 博客系统 MVP - API规范文档  这是一个基于 Go Gin 框架构建的博客系统，提供用户认证、博文创建和浏览功能。  ## 特性 - JWT token 认证 - Bcrypt 密码加密 - GORM 数据库持久化 - 博文创建和列表 - RESTful API 设计 - CORS 支持  ## 认证流程 1. 用户通过 `/user/login` 接口进行身份验证 2. 服务器验证用户名和密码，返回 JWT token 3. 客户端在后续请求中通过 `Authorization: Bearer <token>` 头部携带 token 4. 服务器验证 token 有效性，提供相应的服务 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: developer@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginUserRequest
 */
export interface LoginUserRequest {
    /**
     * 用户名
     * @type {string}
     * @memberof LoginUserRequest
     */
    username: string;
    /**
     * 密码
     * @type {string}
     * @memberof LoginUserRequest
     */
    password: string;
}

/**
 * Check if a given object implements the LoginUserRequest interface.
 */
export function instanceOfLoginUserRequest(value: object): value is LoginUserRequest {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function LoginUserRequestFromJSON(json: any): LoginUserRequest {
    return LoginUserRequestFromJSONTyped(json, false);
}

export function LoginUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
    };
}

export function LoginUserRequestToJSON(json: any): LoginUserRequest {
    return LoginUserRequestToJSONTyped(json, false);
}

export function LoginUserRequestToJSONTyped(value?: LoginUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
    };
}

