/* tslint:disable */
/* eslint-disable */
/**
 * Assignment 3 - Blog System API
 * Assignment 3 Milestone 1 博客系统 MVP - API规范文档  这是一个基于 Go Gin 框架构建的博客系统，提供用户认证、博文创建和浏览功能。  ## 特性 - JWT token 认证 - Bcrypt 密码加密 - GORM 数据库持久化 - 博文创建和列表 - RESTful API 设计 - CORS 支持  ## 认证流程 1. 用户通过 `/user/login` 接口进行身份验证 2. 服务器验证用户名和密码，返回 JWT token 3. 客户端在后续请求中通过 `Authorization: Bearer <token>` 头部携带 token 4. 服务器验证 token 有效性，提供相应的服务 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: developer@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostResponse
 */
export interface PostResponse {
    /**
     * 博文唯一标识符
     * @type {number}
     * @memberof PostResponse
     */
    id: number;
    /**
     * 博文内容
     * @type {string}
     * @memberof PostResponse
     */
    content: string;
    /**
     * 作者昵称
     * @type {string}
     * @memberof PostResponse
     */
    authorNickname: string;
    /**
     * 创建时间
     * @type {Date}
     * @memberof PostResponse
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the PostResponse interface.
 */
export function instanceOfPostResponse(value: object): value is PostResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('authorNickname' in value) || value['authorNickname'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function PostResponseFromJSON(json: any): PostResponse {
    return PostResponseFromJSONTyped(json, false);
}

export function PostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'content': json['content'],
        'authorNickname': json['author_nickname'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function PostResponseToJSON(json: any): PostResponse {
    return PostResponseToJSONTyped(json, false);
}

export function PostResponseToJSONTyped(value?: PostResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'content': value['content'],
        'author_nickname': value['authorNickname'],
        'created_at': ((value['createdAt']).toISOString()),
    };
}

